### ISSUE TITLE
Set up github actions for isort and black formatter

### ISSUE THREAD

**Issue by shenef** [coderwilson/FFX_TAS_Python#141]

**Comment by jlward** [comment]
Something like [this](https://git-scm.com/book/en/v2/Customizing-Git-An-Example-Git-Enforced-Policy#_an_example_git_enforced_policy) might be easier. I'm not 100% certain we can make the action actually make the change and commit it. This link might be able to force a pre-commit to happen for all clones of the repo. I didn't get a ton of time to read up on it, but it might help.
