### ISSUE TITLE
Automatically set the game speed to x4 during battles

### ISSUE THREAD

**Issue by shenef** [coderwilson/FFX_TAS_Python#143]

**Comment by MrTyton** [comment]
Basic implementation

```python
def speedup_decorator(func):
  def wrapper():
    if (enable_variable...):
        set_game_speed(4)
    func()
    if (enable_variable...):
        set_game_speed(1)
  return wrapper

@speedup_decorator
def battle_func...
```

and then a lot of copy+paste to add the decorator to all the needed funcs

can't do it w/ a module import hack cuz of helper functions

**Comment by MrTyton** [comment]
Other way would be to do it w/ multithreading, check to ensure that battle is active and dialogue isn't playing (for some reason speedup makes dialogue take _forever_), and then set the speed there.
