### ISSUE TITLE
Add install instructions to the readme

### ISSUE THREAD

**Issue by shenef** [coderwilson/FFX_TAS_Python#147]

**Comment by orkaboy** [comment]
I started an effort to compile current information here: https://github.com/orkaboy/FFX_TAS_Python/tree/dev/README

**Comment by orkaboy** [comment]
Tied to PR: #174

**Comment by orkaboy** [comment]
This could potentially be closed now, as the PR has been merged. Either that or add more specifics on what is missing for future work.
