### ISSUE TITLE
Update all saves for the run

### ISSUE THREAD

**Issue by coderwilson** [coderwilson/FFX_TAS_Python#151]

**Comment by orkaboy** [comment]
As per the discussion on discord, this could be automated the following way:

- Add a config parameter named something like "create_save_states"
- In code, check the flag everywhere that a save should be made, and in that case, have the TAS create a save
- Complete a run with this setting and you should have all the save states using the latest run logic

**Comment by coderwilson** [comment]
The code for this is complete, the saves are not. Assigning myself.
