### ISSUE TITLE
Select run type on New Game

### ISSUE THREAD

**Issue by coderwilson** [coderwilson/FFX_TAS_Python#153]
Using the input function, force the user to input something for "full run" vs "Blitzball-learning run" the first time you select New Game. For Blitzball runs, only needs to be selected the first time, any loops will remember the setting. This will prevent the disaster that was RPGLB's five-reset run.

**Comment by orkaboy** [comment]
This is potentially addressed by the config.yaml merge, in the case that it is implemented using those flags.
