### ISSUE TITLE
Move vars to an ini file

### ISSUE THREAD

**Issue by shenef** [coderwilson/FFX_TAS_Python#154]
Those could then be updated if the run is started via launch arguments, a GUI or whatever we decide on.
Until then an ini is a cleaner solution than editing a python file.
https://docs.python.org/3/library/configparser.html

**Comment by orkaboy** [comment]
I made a quick and dirty implementation using pyyaml:
https://github.com/orkaboy/FFX_TAS_Python/tree/dev/config_yaml

Hasn't been fully tested for every single variable, but starting a run with it works. Covers vars, Gamestate/step_counter and some of the RNG variables.

**Comment by orkaboy** [comment]
This could potentially be closed now, as the PR is merged. Either that or add missing features to be implemented.
