### ISSUE TITLE
Valefor Overdrive Kilika farming bug

### ISSUE THREAD

**Issue by orkaboy** [coderwilson/FFX_TAS_Python#206]
When farming for Valefor Overdrive in Kilika woods, the TAS reads from memory that farming isn't done, so it walks between two spots to farm a battle. However, when it goes into a battle, rather than swapping in Yuna/summoning, it immediately flees. This repeats over and over.

Video:
https://youtu.be/LJINmbE9EqE

**Comment by orkaboy** [comment]
I've seen this several times in runs now, so it appears to be a consistent issue. I'm not sure what it's looking for/waiting for, but it's not working out.

**Comment by coderwilson** [comment]
No longer an issue with Terra skip.
