### ISSUE TITLE
Character Check sometimes Fails

### ISSUE THREAD

**Issue by MrTyton** [coderwilson/FFX_TAS_Python#226]
https://github.com/coderwilson/FFX_TAS_Python/blob/088ae6a2cfabae705eb8c3c306dc524f09c29277/battle/main.py#L4674-L4675
https://github.com/coderwilson/FFX_TAS_Python/blob/088ae6a2cfabae705eb8c3c306dc524f09c29277/battle/main.py#L4659-L4672

Sometimes, this doesn't properly see that Tidus is incapacitated, which can cause deaths in Miihen.

**Comment by orkaboy** [comment]
For me, this happened in Moonflow. Hopefully the same fix should apply there.

**Comment by coderwilson** [comment]
This should only happen when the TAS is not properly waiting for the next character's turn to start. Need evidence to the contrary and we can investigate further.

**Comment by coderwilson** [comment]
I haven't seen this in quite some time. Closing bug until we see it again.
